# Generated by Django 5.0.6 on 2024-05-12 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="dates",
        ),
    ]
