# Generated by Django 5.0.6 on 2024-05-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_remove_contact_dates"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("domain", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="faculty_images/")),
                ("description", models.TextField()),
                ("link", models.URLField()),
            ],
        ),
    ]
