# Generated by Django 5.0.6 on 2024-05-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_faculty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faculty",
            old_name="description",
            new_name="Faculty_description",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="image",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="link",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="name",
        ),
        migrations.AddField(
            model_name="faculty",
            name="Faculty_domain",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="faculty",
            name="Faculty_image",
            field=models.ImageField(default="", upload_to="faculty/images"),
        ),
        migrations.AddField(
            model_name="faculty",
            name="Faculty_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
