# Generated by Django 5.0.6 on 2024-05-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_rename_description_faculty_faculty_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="Faculty_description",
            field=models.TextField(default=""),
        ),
    ]
