# Generated by Django 5.0.6 on 2024-05-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_student_publications_ru"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="Faculty_pass",
            field=models.TextField(default=""),
        ),
    ]
