# Generated by Django 5.0.6 on 2024-05-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_faculty_faculty_pass"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="Faculty_pass",
            field=models.CharField(default="", max_length=100),
        ),
    ]
