# Generated by Django 5.0.6 on 2024-05-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_faculty_faculty_pass"),
    ]

    operations = [
        migrations.AddField(
            model_name="publications",
            name="Publication_field",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="publications",
            name="Publication_type",
            field=models.CharField(
                choices=[
                    ("Journal", "Journal"),
                    ("Conference", "Conference"),
                    ("Book Series", "Book Series"),
                    ("Transaction", "Transaction"),
                ],
                default="Journal",
                max_length=20,
            ),
        ),
    ]
