# Generated by Django 5.0.6 on 2024-05-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_publications_publication_field_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ru",
            name="RU_pdf",
        ),
        migrations.AlterField(
            model_name="publications",
            name="Publication_field",
            field=models.CharField(
                choices=[
                    ("RU", "RU"),
                    ("minor", "Minor"),
                    ("mini", "Mini"),
                    ("course_project", "Course Project"),
                ],
                default="RU",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="publications",
            name="Publication_type",
            field=models.CharField(
                choices=[
                    ("journal", "Journal"),
                    ("conference", "Conference"),
                    ("book_series", "Book Series"),
                    ("transaction", "Transaction"),
                ],
                default="journal",
                max_length=20,
            ),
        ),
    ]
