# Generated by Django 5.0.6 on 2024-05-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_remove_ru_ru_pdf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publications",
            name="Publication_field",
            field=models.CharField(
                choices=[
                    ("RU", "RU"),
                    ("minor", "Minor"),
                    ("mini", "Mini"),
                    ("course_project", "Course Project"),
                    ("others", "Others"),
                ],
                default="RU",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="publications",
            name="Publication_type",
            field=models.CharField(
                choices=[
                    ("journal", "Journal"),
                    ("conference", "Conference"),
                    ("book_series", "Book Series"),
                    ("transaction", "Transaction"),
                    ("others", "Others"),
                ],
                default="journal",
                max_length=20,
            ),
        ),
    ]
