# Generated by Django 5.0.6 on 2024-05-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_alter_publications_publication_field_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publications",
            name="Publication_field",
            field=models.CharField(
                choices=[
                    ("faculty", "Faculty"),
                    ("RU", "RU"),
                    ("minor", "Minor"),
                    ("mini", "Mini"),
                    ("course_project", "Course Project"),
                    ("others", "Others"),
                ],
                default="RU",
                max_length=20,
            ),
        ),
    ]
