# Generated by Django 5.0.6 on 2024-05-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_alter_publications_publication_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="Faculty_domain",
            field=models.CharField(
                choices=[
                    ("EDGE-AI", "EDGE-AI"),
                    ("HPC", "HPC"),
                    ("CLOUD", "CLOUD"),
                    ("DATA SCIENCE", "DATA SCIENCE"),
                ],
                default="EDGE-AI",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="Faculty_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="publications",
            name="Publication_field",
            field=models.CharField(
                choices=[
                    ("faculty", "Faculty"),
                    ("REU", "REU"),
                    ("minor", "Minor"),
                    ("mini", "Mini"),
                    ("course_project", "Course Project"),
                    ("others", "Others"),
                ],
                default="REU",
                max_length=20,
            ),
        ),
    ]
