# Generated by Django 5.0.6 on 2024-05-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_alter_faculty_faculty_domain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ru",
            name="code_link",
            field=models.URLField(default="#"),
        ),
        migrations.AddField(
            model_name="ru",
            name="paper_link",
            field=models.URLField(default="#"),
        ),
        migrations.AddField(
            model_name="ru",
            name="problem_statement",
            field=models.TextField(default=""),
        ),
    ]
