# Generated by Django 5.0.6 on 2024-05-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_ru_code_link_ru_paper_link_ru_problem_statement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ru",
            name="code_link",
        ),
        migrations.RemoveField(
            model_name="ru",
            name="paper_link",
        ),
        migrations.AddField(
            model_name="publications",
            name="code_link",
            field=models.URLField(default="#"),
        ),
        migrations.AddField(
            model_name="publications",
            name="paper_link",
            field=models.URLField(default="#"),
        ),
    ]
