# Generated by Django 5.0.6 on 2024-05-23 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_remove_ru_code_link_remove_ru_paper_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publications",
            name="Faculty_id",
        ),
        migrations.AddField(
            model_name="publications",
            name="author_type",
            field=models.CharField(
                choices=[("faculty", "Faculty"), ("student", "Student")],
                default="faculty",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="publications",
            name="faculty_author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.faculty",
            ),
        ),
        migrations.AddField(
            model_name="publications",
            name="student_author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.student",
            ),
        ),
        migrations.AddField(
            model_name="publications",
            name="year",
            field=models.IntegerField(default=2023),
        ),
    ]
