# Generated by Django 5.0.6 on 2024-05-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_remove_publications_faculty_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publications",
            name="author_type",
        ),
        migrations.RemoveField(
            model_name="publications",
            name="faculty_author",
        ),
        migrations.RemoveField(
            model_name="publications",
            name="student_author",
        ),
        migrations.AddField(
            model_name="publications",
            name="faculty_authors",
            field=models.ManyToManyField(
                related_name="publications_faculty", to="home.faculty"
            ),
        ),
        migrations.AddField(
            model_name="publications",
            name="student_authors",
            field=models.ManyToManyField(
                related_name="publications_student", to="home.student"
            ),
        ),
    ]
