# Generated by Django 5.0.6 on 2024-05-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_remove_publications_author_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publications",
            name="Publication_arch_image",
            field=models.ImageField(default="", upload_to="publications/images"),
        ),
    ]
