# Generated by Django 5.0.6 on 2024-05-28 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_publications_publication_arch_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="ru",
            name="REU_topic",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="ru",
            name="SRN",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="ru",
            name="co_guide_name",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ru",
            name="guide_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="ru",
            name="name_of_the_student",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="ru",
            name="Faculty_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.faculty",
            ),
        ),
        migrations.AlterField(
            model_name="ru",
            name="Student_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.student",
            ),
        ),
    ]
