# Generated by Django 5.0.6 on 2024-06-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0022_ru_reu_topic_ru_srn_ru_co_guide_name_ru_guide_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ru",
            name="problem_statement",
        ),
        migrations.AddField(
            model_name="ru",
            name="year",
            field=models.IntegerField(default=2023),
        ),
    ]
