# Generated by Django 5.0.6 on 2024-06-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0023_remove_ru_problem_statement_ru_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="Faculty_image",
            field=models.ImageField(
                default="default_image.jpg", upload_to="faculty/images"
            ),
        ),
    ]
