# Generated by Django 5.0.6 on 2024-06-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0024_alter_faculty_faculty_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="desc",
            field=models.TextField(default="nan"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.CharField(default="nan", max_length=122),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(default="nan", max_length=122),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(default="nan", max_length=12),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="Faculty_description",
            field=models.TextField(default="nan"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="Faculty_image",
            field=models.ImageField(
                default="images/default_image.png", upload_to="faculty/images"
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="Faculty_name",
            field=models.CharField(default="nan", max_length=100),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="Faculty_pass",
            field=models.CharField(default="nan", max_length=100),
        ),
        migrations.AlterField(
            model_name="publications",
            name="Publication_arch_image",
            field=models.ImageField(
                default="images/default_image.png", upload_to="publications/images"
            ),
        ),
        migrations.AlterField(
            model_name="publications",
            name="Publication_name",
            field=models.CharField(default="nan", max_length=255),
        ),
        migrations.AlterField(
            model_name="publications",
            name="Publication_pdf",
            field=models.FileField(
                default="publications/pdfs/default_pdf.pdf",
                upload_to="publications/pdfs",
            ),
        ),
        migrations.AlterField(
            model_name="publications",
            name="code_link",
            field=models.URLField(default="https://default-link.com"),
        ),
        migrations.AlterField(
            model_name="publications",
            name="paper_link",
            field=models.URLField(default="https://default-link.com"),
        ),
        migrations.AlterField(
            model_name="ru",
            name="REU_topic",
            field=models.TextField(default="nan"),
        ),
        migrations.AlterField(
            model_name="ru",
            name="RU_domain",
            field=models.CharField(default="nan", max_length=255),
        ),
        migrations.AlterField(
            model_name="ru",
            name="SRN",
            field=models.CharField(default="nan", max_length=20),
        ),
        migrations.AlterField(
            model_name="ru",
            name="co_guide_name",
            field=models.CharField(
                blank=True, default="nan", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ru",
            name="guide_name",
            field=models.CharField(default="nan", max_length=100),
        ),
        migrations.AlterField(
            model_name="ru",
            name="name_of_the_student",
            field=models.CharField(default="nan", max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="Student_image",
            field=models.ImageField(
                default="images/default_image.png", upload_to="students/images"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="Student_name",
            field=models.CharField(default="nan", max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="Student_phone_no",
            field=models.CharField(default="nan", max_length=15),
        ),
        migrations.AlterField(
            model_name="student",
            name="Student_roll_no",
            field=models.CharField(default="nan", max_length=20),
        ),
    ]
