# Generated by Django 5.0.6 on 2024-06-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
