# Generated by Django 5.0.6 on 2024-06-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0029_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
