# Generated by Django 5.0.6 on 2024-06-24 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0030_faculty_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publications",
            name="code_link",
        ),
    ]
