# Generated by Django 5.0.6 on 2024-06-24 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0031_remove_publications_code_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publications",
            name="Publication_arch_image",
        ),
    ]
