# Generated by Django 5.0.6 on 2024-06-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0033_faculty_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="ru",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
